# Generated by Django 6.0.1 on 2026-01-25 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/%Y/%m/%d/', verbose_name='解析画像')),
                ('prediction_label', models.CharField(max_length=255, verbose_name='予測ラベル')),
                ('prediction_score', models.FloatField(verbose_name='確信度(%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='解析日時')),
            ],
            options={
                'verbose_name': '解析結果',
                'verbose_name_plural': '解析結果一覧',
            },
        ),
    ]
