# Generated by Django 6.0.1 on 2026-02-03 01:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='解析対象の画像ファイル', upload_to='uploads/%Y/%m/%d/', verbose_name='解析画像')),
                ('original_filename', models.CharField(blank=True, max_length=255, null=True, verbose_name='元のファイル名')),
                ('prediction_label', models.CharField(db_index=True, max_length=255, verbose_name='予測ラベル')),
                ('prediction_score', models.FloatField(help_text='予測の確信度（0-100%）', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)], verbose_name='確信度(%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='解析日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('model_version', models.CharField(blank=True, default='v1.0', max_length=50, verbose_name='モデルバージョン')),
                ('processing_time', models.FloatField(blank=True, help_text='画像解析にかかった時間', null=True, verbose_name='処理時間(秒)')),
            ],
            options={
                'verbose_name': '解析結果',
                'verbose_name_plural': '解析結果一覧',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at', 'prediction_label'], name='predict_ana_created_996e73_idx')],
            },
        ),
    ]
